### PR TITLE
avoid blank screen on failed signin

### LINKED ISSUE #38: Blank screen after two login fail
**Context**
On a Windows 7 computer, with google chrome installed

**What are you trying to achieve or the steps to reproduce ?**
Login with wrong user/password twice

**Which result you had ?**
Blank screen page

[localhost-1520859047284.log](https://github.com/Opla/front/files/1802770/localhost-1520859047284.log)

### PR DESCRIPTION
**Pull request by lunika**
Fix #38

### CODE REVIEW

File: src/shared/reducers/message.js [hunk 1]
```diff
@@ -16,10 +16,24 @@ import {
...
-});
+export const addErrorToState = (state, { error }) => {
+  let message = error;
+
+  if (message instanceof Error) {
+    ({ message } = error);
+  }
+
+  if (typeof message !== "string") {
+    return {
```
Comment (willdurand) [inline src/shared/reducers/message.js]: `return state;`?

Comment (willdurand) [reply src/shared/reducers/message.js]: also I would log an error here because it should not happen.

File: src/shared/sagas/auth.js [hunk 2]
```diff
@@ -22,7 +22,7 @@ function* authenticate({ username, password, provider }) {
 
     yield put(signInComplete({ attributes: response, provider }));
   } catch (error) {
-    yield put(signOutError({ provider, error }));
+    yield put(signOutError({ provider, error: error.message }));
```
Comment (willdurand) [inline src/shared/sagas/auth.js]: with the fix you've done above, there is no need to do this. also, that would be better to pass the full `error` object.

File: tests/shared/reducers/message.test.js [hunk 3]
```diff
@@ -34,4 +37,34 @@ describe("reducers/app", () => {
       message: null,
     });
   });
+
+  describe("test addErrorToState function", () => {
```
Comment (willdurand) [inline tests/shared/reducers/message.test.js]: I would only put the name of the function here, e.g., `describe("addErrorToState()", ....`

File: tests/shared/reducers/message.test.js [hunk 4]
```diff
@@ -34,4 +37,34 @@ describe("reducers/app", () => {
...
+    it("addErrorMessage with a valid string message", () => {
```
Comment (willdurand) [inline tests/shared/reducers/message.test.js]: you should write sentences starting with `it` (which is already added with the `it` function).

```
it("accepts an error as a string", () => {
```

File: tests/shared/reducers/message.test.js [hunk 5]
```diff
@@ -34,4 +37,34 @@ describe("reducers/app", () => {
...
+        error: "An error message",
+      });
+
+      expect(state).toEqual({
+        ...initialState,
+        message: "An error message",
+      });
+    });
+
+    it("addErrorMessage with an Error instance", () => {
```
Comment (willdurand) [inline tests/shared/reducers/message.test.js]:
```
it("accepts an error as a Error object", () => {
```

File: tests/shared/reducers/message.test.js [hunk 6]
```diff
@@ -34,4 +37,34 @@ describe("reducers/app", () => {
...
+        error: Error("An error message"),
+      });
+
+      expect(state).toEqual({
+        ...initialState,
+        message: "An error message",
+      });
+    });
+
+    it("addErrorMessage with a non valid error", () => {
```
Comment (willdurand) [inline tests/shared/reducers/message.test.js]:
```
it("ignores invalid error types", () => {
```

this test really makes me think something should be done. we should not silent this behavior, it is definitely too dangerous.

File: src/shared/reducers/message.js (hunk 1 above)
Comment (lunika) [reply src/shared/reducers/message.js]: Is it allow to return the same state ? I thought you must return a new instance.

File: tests/shared/reducers/message.test.js (hunk 6 above)
Comment (lunika) [reply tests/shared/reducers/message.test.js]: I should throw a new error ? Maybe accepting only a string is to restrictive, all "printable" variable should be allowed, I should also test numbers with something linke

`false === ["string", "number"].includes(typeof message)`

WDYT ?

File: src/shared/reducers/message.js (hunk 1 above)
Comment (willdurand) [reply src/shared/reducers/message.js]: if you dont change it, there is nothing else to do.

File: tests/shared/reducers/message.test.js (hunk 6 above)
Comment (willdurand) [reply tests/shared/reducers/message.test.js]: mmh I think no one would use a number as an error, we should not enforce that.

and yeah, an error for developers would be nice.

**Comment by lunika** [comment]
@willdurand modification made

File: src/shared/reducers/message.js [hunk 7]
```diff
@@ -16,10 +16,22 @@ import {
...
-});
+export const addErrorToState = (state, { error }) => {
+  let message = error;
+
+  if (message instanceof Error) {
+    ({ message } = error);
+  }
+
+  if (typeof message !== "string") {
+    throw new Error("invalid error message. A string is expected here.");
```
Comment (willdurand) [inline src/shared/reducers/message.js]: This is not really accurate since `message` can be either an error or a string. Yet, when the error object is used, it is necessarily a string. I would do that instead:

```
export const addErrorToState = (state, { error }) => {
  let message;
  if (error instanceof Error) {
    message = error.message;
  } else if (typeof error === "string") {
    message = error;
  } else {
    throw new Error("addErrorToState requires either an Error or a string");
  }
};
```

Comment (lunika) [reply src/shared/reducers/message.js]: Done
